- name: Update SSH configuration
  template:
    src: ssh_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart SSH service
    
- name: Copy authorized_keys file
  copy:
    src: authorized_keys
    dest: /root/.ssh/authorized_keys
    mode: 0600
  notify:
    - Restart SSH service
