- name: install required packages
  yum: 
    name: "{{ item }}"          
    state: present               
  with_items:                    
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: add docker repo to /etc/yum.repos.d
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  register: result              

- name: install docker-ce docker-compose
  yum:
    name: "{{ item }}"       
    state: present
  with_items:                    
    - docker-ce
    - docker-compose


- name: create /etc/docker
  file:
    path: "{{ docker_config_dir }}"          
    state: directory

- name: start docker service
  systemd:                         
    name: docker
    state: started
    enabled: true

- name: provide docker-ce configfile
  template:
    src: daemon.json.j2                 
    dest: /etc/docker/daemon.json
  notify: restart docker                  