

- name: Add zabbix repository
  shell:  rpm -Uvh https://repo.zabbix.com/zabbix/5.4/rhel/7/x86_64/zabbix-release-5.4-1.el7.noarch.rpm

- name: Yum zabbix
  yum: 
    pkg: zabbix-agent
    state: latest

